#!/usr/bin/env sh

alias k=kubectl

which nvim >/dev/null && alias vi=nvim
which nvim >/dev/null && alias vim=nvim
alias clip=pbcopy

which bat >/dev/null && alias cat=bat
which eza >/dev/null && alias ls=eza

alias tw=taskwarrior-tui
alias lg=lazygit
