#!/usr/bin/env sh

if type brew &>/dev/null; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

autoload -Uz compinit
compinit

source <(kubectl completion zsh)
eval "$(zoxide init zsh)"
