#!/usr/bin/bash

export NVM_ROOT="/opt/homebrew/opt/nvm"

function init_nvm {
	unalias ${nvm_cmds[*]}
	unset nvm_cmds

	echo "Loading NVM..."
	. "${NVM_ROOT}/nvm.sh" --no-use

	# Load nvm bash_completion
	[ -s "${NVM_ROOT}/etc/bash_completion.d/nvm" ] && source "${NVM_ROOT}/etc/bash_completion.d/nvm"
}

if [ -s "${NVM_ROOT}/nvm.sh" ]; then
	nvm_cmds=(nvm node npm yarn)
	for cmd in ${nvm_cmds}; do
		alias ${cmd}="init_nvm && ${cmd}"
	done
fi
