#!/usr/bin/env sh

export PATH=${HOME}/bin:${PATH}
export PATH=${HOME}/.local/bin:${PATH}

export PATH=${HOME}/go/bin:${PATH}
export PATH=${HOME}/.local/share/coursier/bin:${PATH}
export PATH=${HOME}/.cargo/bin:${PATH}
export PATH=${HOME}/.dotnet/tools:${PATH}
export PATH=${HOME}/.pulumi/bin:${PATH}
export PATH=${HOME}/.local/share/pnpm:${PATH}
export PATH=/snap/bin:${PATH}
export PATH=/usr/local/sbin:${PATH}

export PATH=/usr/lib/node_modules/corepack/shims/:${PATH}
export PATH=${DENO_INSTALL}/bin:${PATH}
export PATH=${PNPM_HOME}:${PATH}

export PATH="/opt/homebrew/opt/libpq/bin:${PATH}"
